package ServerSeite;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.UIManager;

/**  
 *
 * @author alisi
 */
public class Simulator extends javax.swing.JFrame {


  

    /**
     * Creates new form Simulator
     */
    public Simulator() {
        
//        try {
//		    for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
//		        if ("Nimbus".equals(info.getName())) {
//		            UIManager.setLookAndFeel(info.getClassName());
//                            System.out.println(info.getClassName());
//		            break;
//		        }
//		    }
//		} catch (Exception e) {
//		    // If Nimbus is not available, you can set the GUI to another look and feel.
//		}


              
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        circulatingLeftP = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jProgressBarCircLeft = new javax.swing.JProgressBar();
        circulatingRightP = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jProgressBarCircRight = new javax.swing.JProgressBar();
        jProgressBarSuction = new javax.swing.JProgressBar();
        suctionP = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        FreshairP = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jProgressBarFreshAir = new javax.swing.JProgressBar();
        jProgressBarEthylen = new javax.swing.JProgressBar();
        ethylenP = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        damperP = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jProgressBarDamper = new javax.swing.JProgressBar();
        jProgressBarHeater = new javax.swing.JProgressBar();
        heaterP = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jProgressBarCooler = new javax.swing.JProgressBar();
        coolerP = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabelSetTimeCircLeft = new javax.swing.JLabel();
        jLabelSetTimeCircRight = new javax.swing.JLabel();
        jLabelSetTimeSuction = new javax.swing.JLabel();
        jLabelSetTimeFreshAir = new javax.swing.JLabel();
        jLabelSetTimeEthyl = new javax.swing.JLabel();
        jLabelSetTimeDamper = new javax.swing.JLabel();
        jLabelSetTimeHeater = new javax.swing.JLabel();
        jLabelSetTimeCooler = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelT1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelT2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelT3 = new javax.swing.JLabel();
        jLabelT4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabelT5 = new javax.swing.JLabel();
        jLabelT6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabelT7 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelT8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSliderEthylen = new javax.swing.JSlider();
        jSliderCo2 = new javax.swing.JSlider();
        jSliderDamp = new javax.swing.JSlider();
        jSliderTemp = new javax.swing.JSlider();
        jPanel5 = new javax.swing.JPanel();
        jLabelEthylenSoll = new javax.swing.JLabel();
        jLabelEthylenTol = new javax.swing.JLabel();
        jLabelCo2Soll = new javax.swing.JLabel();
        jLabelCo2Tol = new javax.swing.JLabel();
        jLabelDampSoll = new javax.swing.JLabel();
        jLabelDampTol = new javax.swing.JLabel();
        jLabelTempSoll = new javax.swing.JLabel();
        jLabelTempTol = new javax.swing.JLabel();
        jLabelEthylen = new javax.swing.JLabel();
        jLabelCo2 = new javax.swing.JLabel();
        jLabelDamp = new javax.swing.JLabel();
        jLabelTemp = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        circulatingLeftP.setBackground(new java.awt.Color(51, 255, 0));
        circulatingLeftP.setDoubleBuffered(false);

        jLabel6.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabel6.setText("Circ.Left");

        javax.swing.GroupLayout circulatingLeftPLayout = new javax.swing.GroupLayout(circulatingLeftP);
        circulatingLeftP.setLayout(circulatingLeftPLayout);
        circulatingLeftPLayout.setHorizontalGroup(
            circulatingLeftPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circulatingLeftPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        circulatingLeftPLayout.setVerticalGroup(
            circulatingLeftPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, circulatingLeftPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        jProgressBarCircLeft.setValue(20);
        jProgressBarCircLeft.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarCircLeft.setStringPainted(true);

        circulatingRightP.setBackground(new java.awt.Color(51, 255, 0));
        circulatingRightP.setDoubleBuffered(false);

        jLabel11.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabel11.setText("Circ.right");

        javax.swing.GroupLayout circulatingRightPLayout = new javax.swing.GroupLayout(circulatingRightP);
        circulatingRightP.setLayout(circulatingRightPLayout);
        circulatingRightPLayout.setHorizontalGroup(
            circulatingRightPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circulatingRightPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        circulatingRightPLayout.setVerticalGroup(
            circulatingRightPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, circulatingRightPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        jProgressBarCircRight.setValue(20);
        jProgressBarCircRight.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarCircRight.setStringPainted(true);

        jProgressBarSuction.setValue(20);
        jProgressBarSuction.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarSuction.setStringPainted(true);

        suctionP.setBackground(new java.awt.Color(51, 255, 0));
        suctionP.setDoubleBuffered(false);

        jLabel12.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabel12.setText("Suction");

        javax.swing.GroupLayout suctionPLayout = new javax.swing.GroupLayout(suctionP);
        suctionP.setLayout(suctionPLayout);
        suctionPLayout.setHorizontalGroup(
            suctionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suctionPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        suctionPLayout.setVerticalGroup(
            suctionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suctionPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        FreshairP.setBackground(new java.awt.Color(51, 255, 0));
        FreshairP.setDoubleBuffered(false);

        jLabel13.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabel13.setText("FreshAir");

        javax.swing.GroupLayout FreshairPLayout = new javax.swing.GroupLayout(FreshairP);
        FreshairP.setLayout(FreshairPLayout);
        FreshairPLayout.setHorizontalGroup(
            FreshairPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FreshairPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FreshairPLayout.setVerticalGroup(
            FreshairPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FreshairPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );

        jProgressBarFreshAir.setValue(20);
        jProgressBarFreshAir.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarFreshAir.setStringPainted(true);

        jProgressBarEthylen.setValue(20);
        jProgressBarEthylen.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarEthylen.setStringPainted(true);

        ethylenP.setBackground(new java.awt.Color(51, 255, 0));
        ethylenP.setDoubleBuffered(false);

        jLabel14.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabel14.setText("Ethlylen");

        javax.swing.GroupLayout ethylenPLayout = new javax.swing.GroupLayout(ethylenP);
        ethylenP.setLayout(ethylenPLayout);
        ethylenPLayout.setHorizontalGroup(
            ethylenPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ethylenPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ethylenPLayout.setVerticalGroup(
            ethylenPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ethylenPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14))
        );

        damperP.setBackground(new java.awt.Color(51, 255, 0));
        damperP.setDoubleBuffered(false);

        jLabel15.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabel15.setText("Damper");

        javax.swing.GroupLayout damperPLayout = new javax.swing.GroupLayout(damperP);
        damperP.setLayout(damperPLayout);
        damperPLayout.setHorizontalGroup(
            damperPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(damperPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        damperPLayout.setVerticalGroup(
            damperPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, damperPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15))
        );

        jProgressBarDamper.setValue(20);
        jProgressBarDamper.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarDamper.setStringPainted(true);

        jProgressBarHeater.setValue(20);
        jProgressBarHeater.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarHeater.setStringPainted(true);

        heaterP.setBackground(new java.awt.Color(51, 255, 0));
        heaterP.setDoubleBuffered(false);

        jLabel16.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabel16.setText("Heater");

        javax.swing.GroupLayout heaterPLayout = new javax.swing.GroupLayout(heaterP);
        heaterP.setLayout(heaterPLayout);
        heaterPLayout.setHorizontalGroup(
            heaterPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heaterPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        heaterPLayout.setVerticalGroup(
            heaterPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, heaterPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16))
        );

        jProgressBarCooler.setValue(20);
        jProgressBarCooler.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarCooler.setStringPainted(true);

        coolerP.setBackground(new java.awt.Color(51, 255, 0));
        coolerP.setDoubleBuffered(false);

        jLabel17.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabel17.setText("Cooler");

        javax.swing.GroupLayout coolerPLayout = new javax.swing.GroupLayout(coolerP);
        coolerP.setLayout(coolerPLayout);
        coolerPLayout.setHorizontalGroup(
            coolerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coolerPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        coolerPLayout.setVerticalGroup(
            coolerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coolerPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );

        jLabelSetTimeCircLeft.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelSetTimeCircLeft.setText("jLabel9");

        jLabelSetTimeCircRight.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelSetTimeCircRight.setText("jLabel10");

        jLabelSetTimeSuction.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelSetTimeSuction.setText("jLabel11");

        jLabelSetTimeFreshAir.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelSetTimeFreshAir.setText("jLabel12");

        jLabelSetTimeEthyl.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelSetTimeEthyl.setText("jLabel13");

        jLabelSetTimeDamper.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelSetTimeDamper.setText("jLabel14");

        jLabelSetTimeHeater.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelSetTimeHeater.setText("jLabel15");

        jLabelSetTimeCooler.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelSetTimeCooler.setText("jLabel16");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coolerP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heaterP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(damperP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ethylenP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FreshairP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suctionP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(circulatingRightP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(circulatingLeftP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelSetTimeHeater, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSetTimeDamper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSetTimeEthyl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSetTimeCooler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSetTimeSuction, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addComponent(jLabelSetTimeFreshAir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelSetTimeCircLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSetTimeCircRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBarHeater, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBarCooler, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBarDamper, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBarEthylen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBarFreshAir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBarSuction, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBarCircRight, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBarCircLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarCircLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeCircLeft))
                    .addComponent(circulatingLeftP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarCircRight, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeCircRight))
                    .addComponent(circulatingRightP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarSuction, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeSuction))
                    .addComponent(suctionP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarFreshAir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeFreshAir))
                    .addComponent(FreshairP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarEthylen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeEthyl))
                    .addComponent(ethylenP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarDamper, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeDamper))
                    .addComponent(damperP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarHeater, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeHeater))
                    .addComponent(heaterP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarCooler, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeCooler))
                    .addComponent(coolerP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("T1");

        jLabelT1.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelT1.setText("jLabel8");

        jLabel9.setText("T2");

        jLabelT2.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelT2.setText("jLabel8");

        jLabel18.setText("T3");

        jLabelT3.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelT3.setText("jLabel8");

        jLabelT4.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelT4.setText("jLabel8");

        jLabel21.setText("T4");

        jLabel22.setText("T5");

        jLabelT5.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelT5.setText("jLabel8");

        jLabelT6.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelT6.setText("jLabel8");

        jLabel25.setText("T6");

        jLabelT7.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelT7.setText("jLabel8");

        jLabel27.setText("T7");

        jLabel28.setText("T8");

        jLabelT8.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelT8.setText("jLabel8");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelT1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelT2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelT3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelT4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelT5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelT6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelT7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelT8)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelT1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelT2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabelT3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabelT4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabelT5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabelT6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabelT7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabelT8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSliderEthylen.setFont(new java.awt.Font("PibotoLt", 0, 10)); // NOI18N
        jSliderEthylen.setMajorTickSpacing(1);
        jSliderEthylen.setMaximum(10);
        jSliderEthylen.setMinorTickSpacing(1);
        jSliderEthylen.setPaintLabels(true);
        jSliderEthylen.setPaintTicks(true);
        jSliderEthylen.setValue(0);
        jSliderEthylen.setAutoscrolls(true);
        jSliderEthylen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ethyl. in ppm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("PibotoLt", 0, 10))); // NOI18N
        jSliderEthylen.setPreferredSize(new java.awt.Dimension(200, 65));
        jSliderEthylen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderEthylenStateChanged(evt);
            }
        });

        jSliderCo2.setFont(new java.awt.Font("PibotoLt", 0, 10)); // NOI18N
        jSliderCo2.setMajorTickSpacing(1);
        jSliderCo2.setMaximum(6);
        jSliderCo2.setMinorTickSpacing(1);
        jSliderCo2.setPaintLabels(true);
        jSliderCo2.setPaintTicks(true);
        jSliderCo2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CO² in ppm 1000", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("PibotoLt", 0, 10))); // NOI18N
        jSliderCo2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderCo2StateChanged(evt);
            }
        });

        jSliderDamp.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jSliderDamp.setMajorTickSpacing(10);
        jSliderDamp.setMinorTickSpacing(10);
        jSliderDamp.setPaintLabels(true);
        jSliderDamp.setPaintTicks(true);
        jSliderDamp.setValue(0);
        jSliderDamp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Damp in %", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("PibotoLt", 0, 10))); // NOI18N
        jSliderDamp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderDampStateChanged(evt);
            }
        });

        jSliderTemp.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jSliderTemp.setMajorTickSpacing(10);
        jSliderTemp.setMaximum(40);
        jSliderTemp.setMinorTickSpacing(5);
        jSliderTemp.setPaintLabels(true);
        jSliderTemp.setPaintTicks(true);
        jSliderTemp.setValue(0);
        jSliderTemp.setAutoscrolls(true);
        jSliderTemp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Temp in C°", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("PibotoLt", 0, 10)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("PibotoLt", 0, 10))); // NOI18N
        jSliderTemp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderTempStateChanged(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelEthylenSoll.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelEthylenSoll.setText("EthylenSoll ");

        jLabelEthylenTol.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelEthylenTol.setText("EthylenTol");

        jLabelCo2Soll.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelCo2Soll.setText("Co2Soll");

        jLabelCo2Tol.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelCo2Tol.setText("Co2Tol");

        jLabelDampSoll.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelDampSoll.setText("DampSoll");

        jLabelDampTol.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelDampTol.setText("DampTol");

        jLabelTempSoll.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelTempSoll.setText("TempSoll");

        jLabelTempTol.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelTempTol.setText("TempTol");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEthylenTol, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCo2Soll, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCo2Tol, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDampSoll, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTempSoll)
                    .addComponent(jLabelTempTol)
                    .addComponent(jLabelDampTol, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelEthylenSoll)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelEthylenSoll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEthylenTol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCo2Soll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCo2Tol)
                .addGap(18, 18, 18)
                .addComponent(jLabelDampSoll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDampTol)
                .addGap(18, 18, 18)
                .addComponent(jLabelTempSoll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTempTol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelEthylen.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelEthylen.setText("jLabel8");

        jLabelCo2.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelCo2.setText("jLabel8");

        jLabelDamp.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelDamp.setText("jLabel8");

        jLabelTemp.setFont(new java.awt.Font("PibotoLt", 0, 12)); // NOI18N
        jLabelTemp.setText("jLabel8");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSliderCo2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCo2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSliderEthylen, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEthylen))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSliderDamp, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDamp))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSliderTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTemp)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSliderEthylen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEthylen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSliderCo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCo2))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderDamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabelDamp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabelTemp))))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderTempStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderTempStateChanged
        //  int value=this.jSliderTemp.getValue()
//        float x=this.getjSliderTemp().getValue();
//        x=x/10;
        this.getjLabelTemp().setText(String.valueOf(this.getjSliderTemp().getValue()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderTempStateChanged

    private void jSliderDampStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderDampStateChanged
        // TODO add your handling code here:
        this.getjLabelDamp().setText(String.valueOf(this.getjSliderDamp().getValue()));
    }//GEN-LAST:event_jSliderDampStateChanged

    private void jSliderCo2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderCo2StateChanged
        // TODO add your handling code here:
        this.getjLabelCo2().setText(String.valueOf(this.getjSliderCo2().getValue()));
    }//GEN-LAST:event_jSliderCo2StateChanged

    private void jSliderEthylenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderEthylenStateChanged
        // TODO add your handling code here:
        this.getjLabelEthylen().setText(String.valueOf(this.getjSliderEthylen().getValue()));
    }//GEN-LAST:event_jSliderEthylenStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FreshairP;
    private javax.swing.JPanel circulatingLeftP;
    private javax.swing.JPanel circulatingRightP;
    private javax.swing.JPanel coolerP;
    private javax.swing.JPanel damperP;
    private javax.swing.JPanel ethylenP;
    private javax.swing.JPanel heaterP;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCo2;
    private javax.swing.JLabel jLabelCo2Soll;
    private javax.swing.JLabel jLabelCo2Tol;
    private javax.swing.JLabel jLabelDamp;
    private javax.swing.JLabel jLabelDampSoll;
    private javax.swing.JLabel jLabelDampTol;
    private javax.swing.JLabel jLabelEthylen;
    private javax.swing.JLabel jLabelEthylenSoll;
    private javax.swing.JLabel jLabelEthylenTol;
    private javax.swing.JLabel jLabelSetTimeCircLeft;
    private javax.swing.JLabel jLabelSetTimeCircRight;
    private javax.swing.JLabel jLabelSetTimeCooler;
    private javax.swing.JLabel jLabelSetTimeDamper;
    private javax.swing.JLabel jLabelSetTimeEthyl;
    private javax.swing.JLabel jLabelSetTimeFreshAir;
    private javax.swing.JLabel jLabelSetTimeHeater;
    private javax.swing.JLabel jLabelSetTimeSuction;
    private javax.swing.JLabel jLabelT1;
    private javax.swing.JLabel jLabelT2;
    private javax.swing.JLabel jLabelT3;
    private javax.swing.JLabel jLabelT4;
    private javax.swing.JLabel jLabelT5;
    private javax.swing.JLabel jLabelT6;
    private javax.swing.JLabel jLabelT7;
    private javax.swing.JLabel jLabelT8;
    private javax.swing.JLabel jLabelTemp;
    private javax.swing.JLabel jLabelTempSoll;
    private javax.swing.JLabel jLabelTempTol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBarCircLeft;
    private javax.swing.JProgressBar jProgressBarCircRight;
    private javax.swing.JProgressBar jProgressBarCooler;
    private javax.swing.JProgressBar jProgressBarDamper;
    private javax.swing.JProgressBar jProgressBarEthylen;
    private javax.swing.JProgressBar jProgressBarFreshAir;
    private javax.swing.JProgressBar jProgressBarHeater;
    private javax.swing.JProgressBar jProgressBarSuction;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSliderCo2;
    private javax.swing.JSlider jSliderDamp;
    private javax.swing.JSlider jSliderEthylen;
    private javax.swing.JSlider jSliderTemp;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel suctionP;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the FreshairP
     */
    public javax.swing.JPanel getFreshairP() {
        return FreshairP;
    }

    /**
     * @param FreshairP the FreshairP to set
     */
    public void setFreshairP(javax.swing.JPanel FreshairP) {
        this.FreshairP = FreshairP;
    }

    /**
     * @return the circulatingLeftP
     */
    public javax.swing.JPanel getCirculatingLeftP() {
        return circulatingLeftP;
    }

    /**
     * @param circulatingLeftP the circulatingLeftP to set
     */
    public void setCirculatingLeftP(javax.swing.JPanel circulatingLeftP) {
        this.circulatingLeftP = circulatingLeftP;
    }

    /**
     * @return the circulatingRightP
     */
    public javax.swing.JPanel getCirculatingRightP() {
        return circulatingRightP;
    }

    /**
     * @param circulatingRightP the circulatingRightP to set
     */
    public void setCirculatingRightP(javax.swing.JPanel circulatingRightP) {
        this.circulatingRightP = circulatingRightP;
    }

    /**
     * @return the coolerP
     */
    public javax.swing.JPanel getCoolerP() {
        return coolerP;
    }

    /**
     * @param coolerP the coolerP to set
     */
    public void setCoolerP(javax.swing.JPanel coolerP) {
        this.coolerP = coolerP;
    }

    /**
     * @return the damperP
     */
    public javax.swing.JPanel getDamperP() {
        return damperP;
    }

    /**
     * @param damperP the damperP to set
     */
    public void setDamperP(javax.swing.JPanel damperP) {
        this.damperP = damperP;
    }

    /**
     * @return the ethylenP
     */
    public javax.swing.JPanel getEthylenP() {
        return ethylenP;
    }

    /**
     * @param ethylenP the ethylenP to set
     */
    public void setEthylenP(javax.swing.JPanel ethylenP) {
        this.ethylenP = ethylenP;
    }

    /**
     * @return the heaterP
     */
    public javax.swing.JPanel getHeaterP() {
        return heaterP;
    }

    /**
     * @param heaterP the heaterP to set
     */
    public void setHeaterP(javax.swing.JPanel heaterP) {
        this.heaterP = heaterP;
    }

   
    /**
     * @return the jLabel11
     */
    public javax.swing.JLabel getjLabel11() {
        return jLabel11;
    }

    /**
     * @param jLabel11 the jLabel11 to set
     */
    public void setjLabel11(javax.swing.JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    /**
     * @return the jLabel12
     */
    public javax.swing.JLabel getjLabel12() {
        return jLabel12;
    }

    /**
     * @param jLabel12 the jLabel12 to set
     */
    public void setjLabel12(javax.swing.JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    /**
     * @return the jLabel13
     */
    public javax.swing.JLabel getjLabel13() {
        return jLabel13;
    }

    /**
     * @param jLabel13 the jLabel13 to set
     */
    public void setjLabel13(javax.swing.JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    /**
     * @return the jLabel14
     */
    public javax.swing.JLabel getjLabel14() {
        return jLabel14;
    }

    /**
     * @param jLabel14 the jLabel14 to set
     */
    public void setjLabel14(javax.swing.JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    /**
     * @return the jLabel15
     */
    public javax.swing.JLabel getjLabel15() {
        return jLabel15;
    }

    /**
     * @param jLabel15 the jLabel15 to set
     */
    public void setjLabel15(javax.swing.JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    /**
     * @return the jLabel16
     */
    public javax.swing.JLabel getjLabel16() {
        return jLabel16;
    }

    /**
     * @param jLabel16 the jLabel16 to set
     */
    public void setjLabel16(javax.swing.JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    /**
     * @return the jLabel17
     */
    public javax.swing.JLabel getjLabel17() {
        return jLabel17;
    }

    /**
     * @param jLabel17 the jLabel17 to set
     */
    public void setjLabel17(javax.swing.JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel6
     */
    public javax.swing.JLabel getjLabel6() {
        return jLabel6;
    }

    /**
     * @param jLabel6 the jLabel6 to set
     */
    public void setjLabel6(javax.swing.JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    

    /**
     * @return the jLabelCo2Soll
     */
    public javax.swing.JLabel getjLabelCo2Soll() {
        return jLabelCo2Soll;
    }

    /**
     * @param jLabelCo2Soll the jLabelCo2Soll to set
     */
    public void setjLabelCo2Soll(javax.swing.JLabel jLabelCo2Soll) {
        this.jLabelCo2Soll = jLabelCo2Soll;
    }

    /**
     * @return the jLabelCo2Tol
     */
    public javax.swing.JLabel getjLabelCo2Tol() {
        return jLabelCo2Tol;
    }

    /**
     * @param jLabelCo2Tol the jLabelCo2Tol to set
     */
    public void setjLabelCo2Tol(javax.swing.JLabel jLabelCo2Tol) {
        this.jLabelCo2Tol = jLabelCo2Tol;
    }

   
    /**
     * @return the jLabelDampSoll
     */
    public javax.swing.JLabel getjLabelDampSoll() {
        return jLabelDampSoll;
    }

    /**
     * @param jLabelDampSoll the jLabelDampSoll to set
     */
    public void setjLabelDampSoll(javax.swing.JLabel jLabelDampSoll) {
        this.jLabelDampSoll = jLabelDampSoll;
    }

    /**
     * @return the jLabelDampTol
     */
    public javax.swing.JLabel getjLabelDampTol() {
        return jLabelDampTol;
    }

    /**
     * @param jLabelDampTol the jLabelDampTol to set
     */
    public void setjLabelDampTol(javax.swing.JLabel jLabelDampTol) {
        this.jLabelDampTol = jLabelDampTol;
    }

   
    /**
     * @return the jLabelEthylenSoll
     */
    public javax.swing.JLabel getjLabelEthylenSoll() {
        return jLabelEthylenSoll;
    }

    /**
     * @param jLabelEthylenSoll the jLabelEthylenSoll to set
     */
    public void setjLabelEthylenSoll(javax.swing.JLabel jLabelEthylenSoll) {
        this.jLabelEthylenSoll = jLabelEthylenSoll;
    }

    /**
     * @return the jLabelEthylenTol
     */
    public javax.swing.JLabel getjLabelEthylenTol() {
        return jLabelEthylenTol;
    }

    /**
     * @param jLabelEthylenTol the jLabelEthylenTol to set
     */
    public void setjLabelEthylenTol(javax.swing.JLabel jLabelEthylenTol) {
        this.jLabelEthylenTol = jLabelEthylenTol;
    }

    /**
     * @return the jLabelSetTimeCircLeft
     */
    public javax.swing.JLabel getjLabelSetTimeCircLeft() {
        return jLabelSetTimeCircLeft;
    }

    /**
     * @param jLabelSetTimeCircLeft the jLabelSetTimeCircLeft to set
     */
    public void setjLabelSetTimeCircLeft(javax.swing.JLabel jLabelSetTimeCircLeft) {
        this.jLabelSetTimeCircLeft = jLabelSetTimeCircLeft;
    }

    /**
     * @return the jLabelSetTimeCircRight
     */
    public javax.swing.JLabel getjLabelSetTimeCircRight() {
        return jLabelSetTimeCircRight;
    }

    /**
     * @param jLabelSetTimeCircRight the jLabelSetTimeCircRight to set
     */
    public void setjLabelSetTimeCircRight(javax.swing.JLabel jLabelSetTimeCircRight) {
        this.jLabelSetTimeCircRight = jLabelSetTimeCircRight;
    }

    /**
     * @return the jLabelSetTimeCooler
     */
    public javax.swing.JLabel getjLabelSetTimeCooler() {
        return jLabelSetTimeCooler;
    }

    /**
     * @param jLabelSetTimeCooler the jLabelSetTimeCooler to set
     */
    public void setjLabelSetTimeCooler(javax.swing.JLabel jLabelSetTimeCooler) {
        this.jLabelSetTimeCooler = jLabelSetTimeCooler;
    }

    /**
     * @return the jLabelSetTimeDamper
     */
    public javax.swing.JLabel getjLabelSetTimeDamper() {
        return jLabelSetTimeDamper;
    }

    /**
     * @param jLabelSetTimeDamper the jLabelSetTimeDamper to set
     */
    public void setjLabelSetTimeDamper(javax.swing.JLabel jLabelSetTimeDamper) {
        this.jLabelSetTimeDamper = jLabelSetTimeDamper;
    }

    /**
     * @return the jLabelSetTimeEthyl
     */
    public javax.swing.JLabel getjLabelSetTimeEthyl() {
        return jLabelSetTimeEthyl;
    }

    /**
     * @param jLabelSetTimeEthyl the jLabelSetTimeEthyl to set
     */
    public void setjLabelSetTimeEthyl(javax.swing.JLabel jLabelSetTimeEthyl) {
        this.jLabelSetTimeEthyl = jLabelSetTimeEthyl;
    }

    /**
     * @return the jLabelSetTimeFreshAir
     */
    public javax.swing.JLabel getjLabelSetTimeFreshAir() {
        return jLabelSetTimeFreshAir;
    }

    /**
     * @param jLabelSetTimeFreshAir the jLabelSetTimeFreshAir to set
     */
    public void setjLabelSetTimeFreshAir(javax.swing.JLabel jLabelSetTimeFreshAir) {
        this.jLabelSetTimeFreshAir = jLabelSetTimeFreshAir;
    }

    /**
     * @return the jLabelSetTimeHeater
     */
    public javax.swing.JLabel getjLabelSetTimeHeater() {
        return jLabelSetTimeHeater;
    }

    /**
     * @param jLabelSetTimeHeater the jLabelSetTimeHeater to set
     */
    public void setjLabelSetTimeHeater(javax.swing.JLabel jLabelSetTimeHeater) {
        this.jLabelSetTimeHeater = jLabelSetTimeHeater;
    }

    /**
     * @return the jLabelSetTimeSuction
     */
    public javax.swing.JLabel getjLabelSetTimeSuction() {
        return jLabelSetTimeSuction;
    }

    /**
     * @param jLabelSetTimeSuction the jLabelSetTimeSuction to set
     */
    public void setjLabelSetTimeSuction(javax.swing.JLabel jLabelSetTimeSuction) {
        this.jLabelSetTimeSuction = jLabelSetTimeSuction;
    }

    
    /**
     * @return the jLabelTempSoll
     */
    public javax.swing.JLabel getjLabelTempSoll() {
        return jLabelTempSoll;
    }

    /**
     * @param jLabelTempSoll the jLabelTempSoll to set
     */
    public void setjLabelTempSoll(javax.swing.JLabel jLabelTempSoll) {
        this.jLabelTempSoll = jLabelTempSoll;
    }

    /**
     * @return the jLabelTempTol
     */
    public javax.swing.JLabel getjLabelTempTol() {
        return jLabelTempTol;
    }

    /**
     * @param jLabelTempTol the jLabelTempTol to set
     */
    public void setjLabelTempTol(javax.swing.JLabel jLabelTempTol) {
        this.jLabelTempTol = jLabelTempTol;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel4
     */
    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    /**
     * @param jPanel4 the jPanel4 to set
     */
    public void setjPanel4(javax.swing.JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    /**
     * @return the jProgressBarCircLeft
     */
    public javax.swing.JProgressBar getjProgressBarCircLeft() {
        return jProgressBarCircLeft;
    }

    /**
     * @param jProgressBarCircLeft the jProgressBarCircLeft to set
     */
    public void setjProgressBarCircLeft(javax.swing.JProgressBar jProgressBarCircLeft) {
        this.jProgressBarCircLeft = jProgressBarCircLeft;
    }

    /**
     * @return the jProgressBarCircRight
     */
    public javax.swing.JProgressBar getjProgressBarCircRight() {
        return jProgressBarCircRight;
    }

    /**
     * @param jProgressBarCircRight the jProgressBarCircRight to set
     */
    public void setjProgressBarCircRight(javax.swing.JProgressBar jProgressBarCircRight) {
        this.jProgressBarCircRight = jProgressBarCircRight;
    }

    /**
     * @return the jProgressBarCooler
     */
    public javax.swing.JProgressBar getjProgressBarCooler() {
        return jProgressBarCooler;
    }

    /**
     * @param jProgressBarCooler the jProgressBarCooler to set
     */
    public void setjProgressBarCooler(javax.swing.JProgressBar jProgressBarCooler) {
        this.jProgressBarCooler = jProgressBarCooler;
    }

    /**
     * @return the jProgressBarDamper
     */
    public javax.swing.JProgressBar getjProgressBarDamper() {
        return jProgressBarDamper;
    }

    /**
     * @param jProgressBarDamper the jProgressBarDamper to set
     */
    public void setjProgressBarDamper(javax.swing.JProgressBar jProgressBarDamper) {
        this.jProgressBarDamper = jProgressBarDamper;
    }

    /**
     * @return the jProgressBarEthylen
     */
    public javax.swing.JProgressBar getjProgressBarEthylen() {
        return jProgressBarEthylen;
    }

    /**
     * @param jProgressBarEthylen the jProgressBarEthylen to set
     */
    public void setjProgressBarEthylen(javax.swing.JProgressBar jProgressBarEthylen) {
        this.jProgressBarEthylen = jProgressBarEthylen;
    }

    /**
     * @return the jProgressBarFreshAir
     */
    public javax.swing.JProgressBar getjProgressBarFreshAir() {
        return jProgressBarFreshAir;
    }

    /**
     * @param jProgressBarFreshAir the jProgressBarFreshAir to set
     */
    public void setjProgressBarFreshAir(javax.swing.JProgressBar jProgressBarFreshAir) {
        this.jProgressBarFreshAir = jProgressBarFreshAir;
    }

    /**
     * @return the jProgressBarHeater
     */
    public javax.swing.JProgressBar getjProgressBarHeater() {
        return jProgressBarHeater;
    }

    /**
     * @param jProgressBarHeater the jProgressBarHeater to set
     */
    public void setjProgressBarHeater(javax.swing.JProgressBar jProgressBarHeater) {
        this.jProgressBarHeater = jProgressBarHeater;
    }

    /**
     * @return the jProgressBarSuction
     */
    public javax.swing.JProgressBar getjProgressBarSuction() {
        return jProgressBarSuction;
    }

    /**
     * @param jProgressBarSuction the jProgressBarSuction to set
     */
    public void setjProgressBarSuction(javax.swing.JProgressBar jProgressBarSuction) {
        this.jProgressBarSuction = jProgressBarSuction;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jSliderCo2
     */
    public javax.swing.JSlider getjSliderCo2() {
        return jSliderCo2;
    }

    /**
     * @param jSliderCo2 the jSliderCo2 to set
     */
    public void setjSliderCo2(javax.swing.JSlider jSliderCo2) {
        this.jSliderCo2 = jSliderCo2;
    }

    /**
     * @return the jSliderDamp
     */
    public javax.swing.JSlider getjSliderDamp() {
        return jSliderDamp;
    }

    /**
     * @param jSliderDamp the jSliderDamp to set
     */
    public void setjSliderDamp(javax.swing.JSlider jSliderDamp) {
        this.jSliderDamp = jSliderDamp;
    }

    /**
     * @return the jSliderEthylen
     */
    public javax.swing.JSlider getjSliderEthylen() {
        return jSliderEthylen;
    }

    /**
     * @param jSliderEthylen the jSliderEthylen to set
     */
    public void setjSliderEthylen(javax.swing.JSlider jSliderEthylen) {
        this.jSliderEthylen = jSliderEthylen;
    }

    /**
     * @return the jSliderTemp
     */
    public javax.swing.JSlider getjSliderTemp() {
        return jSliderTemp;
    }

    /**
     * @param jSliderTemp the jSliderTemp to set
     */
    public void setjSliderTemp(javax.swing.JSlider jSliderTemp) {
        this.jSliderTemp = jSliderTemp;
    }

    /**
     * @return the jTextArea1
     */
    public javax.swing.JTextArea getjTextArea1() {
        return jTextArea1;
    }

    /**
     * @param jTextArea1 the jTextArea1 to set
     */
    public void setjTextArea1(javax.swing.JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    /**
     * @return the suctionP
     */
    public javax.swing.JPanel getSuctionP() {
        return suctionP;
    }

    /**
     * @param suctionP the suctionP to set
     */
    public void setSuctionP(javax.swing.JPanel suctionP) {
        this.suctionP = suctionP;
    }

    /**
     * @return the jLabel18
     */
    public javax.swing.JLabel getjLabel18() {
        return jLabel18;
    }

    /**
     * @param jLabel18 the jLabel18 to set
     */
    public void setjLabel18(javax.swing.JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    /**
     * @return the jLabel21
     */
    public javax.swing.JLabel getjLabel21() {
        return jLabel21;
    }

    /**
     * @param jLabel21 the jLabel21 to set
     */
    public void setjLabel21(javax.swing.JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    /**
     * @return the jLabel22
     */
    public javax.swing.JLabel getjLabel22() {
        return jLabel22;
    }

    /**
     * @param jLabel22 the jLabel22 to set
     */
    public void setjLabel22(javax.swing.JLabel jLabel22) {
        this.jLabel22 = jLabel22;
    }

    /**
     * @return the jLabel25
     */
    public javax.swing.JLabel getjLabel25() {
        return jLabel25;
    }

    /**
     * @param jLabel25 the jLabel25 to set
     */
    public void setjLabel25(javax.swing.JLabel jLabel25) {
        this.jLabel25 = jLabel25;
    }

    /**
     * @return the jLabel27
     */
    public javax.swing.JLabel getjLabel27() {
        return jLabel27;
    }

    /**
     * @param jLabel27 the jLabel27 to set
     */
    public void setjLabel27(javax.swing.JLabel jLabel27) {
        this.jLabel27 = jLabel27;
    }

    /**
     * @return the jLabel28
     */
    public javax.swing.JLabel getjLabel28() {
        return jLabel28;
    }

    /**
     * @param jLabel28 the jLabel28 to set
     */
    public void setjLabel28(javax.swing.JLabel jLabel28) {
        this.jLabel28 = jLabel28;
    }

    /**
     * @return the jLabel7
     */
    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    /**
     * @param jLabel7 the jLabel7 to set
     */
    public void setjLabel7(javax.swing.JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    /**
     * @return the jLabel9
     */
    public javax.swing.JLabel getjLabel9() {
        return jLabel9;
    }

    /**
     * @param jLabel9 the jLabel9 to set
     */
    public void setjLabel9(javax.swing.JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    /**
     * @return the jLabelT1
     */
    public javax.swing.JLabel getjLabelT1() {
        return jLabelT1;
    }

    /**
     * @param jLabelT1 the jLabelT1 to set
     */
    public void setjLabelT1(javax.swing.JLabel jLabelT1) {
        this.jLabelT1 = jLabelT1;
    }

    /**
     * @return the jLabelT2
     */
    public javax.swing.JLabel getjLabelT2() {
        return jLabelT2;
    }

    /**
     * @param jLabelT2 the jLabelT2 to set
     */
    public void setjLabelT2(javax.swing.JLabel jLabelT2) {
        this.jLabelT2 = jLabelT2;
    }

    /**
     * @return the jLabelT3
     */
    public javax.swing.JLabel getjLabelT3() {
        return jLabelT3;
    }

    /**
     * @param jLabelT3 the jLabelT3 to set
     */
    public void setjLabelT3(javax.swing.JLabel jLabelT3) {
        this.jLabelT3 = jLabelT3;
    }

    /**
     * @return the jLabelT4
     */
    public javax.swing.JLabel getjLabelT4() {
        return jLabelT4;
    }

    /**
     * @param jLabelT4 the jLabelT4 to set
     */
    public void setjLabelT4(javax.swing.JLabel jLabelT4) {
        this.jLabelT4 = jLabelT4;
    }

    /**
     * @return the jLabelT5
     */
    public javax.swing.JLabel getjLabelT5() {
        return jLabelT5;
    }

    /**
     * @param jLabelT5 the jLabelT5 to set
     */
    public void setjLabelT5(javax.swing.JLabel jLabelT5) {
        this.jLabelT5 = jLabelT5;
    }

    /**
     * @return the jLabelT6
     */
    public javax.swing.JLabel getjLabelT6() {
        return jLabelT6;
    }

    /**
     * @param jLabelT6 the jLabelT6 to set
     */
    public void setjLabelT6(javax.swing.JLabel jLabelT6) {
        this.jLabelT6 = jLabelT6;
    }

    /**
     * @return the jLabelT7
     */
    public javax.swing.JLabel getjLabelT7() {
        return jLabelT7;
    }

    /**
     * @param jLabelT7 the jLabelT7 to set
     */
    public void setjLabelT7(javax.swing.JLabel jLabelT7) {
        this.jLabelT7 = jLabelT7;
    }

    /**
     * @return the jLabelT8
     */
    public javax.swing.JLabel getjLabelT8() {
        return jLabelT8;
    }

    /**
     * @param jLabelT8 the jLabelT8 to set
     */
    public void setjLabelT8(javax.swing.JLabel jLabelT8) {
        this.jLabelT8 = jLabelT8;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

   
    /**
     * @return the jLabelCo2
     */
    public javax.swing.JLabel getjLabelCo2() {
        return jLabelCo2;
    }

    /**
     * @param jLabelCo2 the jLabelCo2 to set
     */
    public void setjLabelCo2(javax.swing.JLabel jLabelCo2) {
        this.jLabelCo2 = jLabelCo2;
    }

    /**
     * @return the jLabelDamp
     */
    public javax.swing.JLabel getjLabelDamp() {
        return jLabelDamp;
    }

    /**
     * @param jLabelDamp the jLabelDamp to set
     */
    public void setjLabelDamp(javax.swing.JLabel jLabelDamp) {
        this.jLabelDamp = jLabelDamp;
    }

    /**
     * @return the jLabelEthyl
     */
    public javax.swing.JLabel getjLabelEthyl() {
        return getjLabelEthylen();
    }

    /**
     * @param jLabelEthyl the jLabelEthyl to set
     */
    public void setjLabelEthyl(javax.swing.JLabel jLabelEthyl) {
        this.setjLabelEthylen(jLabelEthyl);
    }

    /**
     * @return the jLabelTemp
     */
    public javax.swing.JLabel getjLabelTemp() {
        return jLabelTemp;
    }

    /**
     * @param jLabelTemp the jLabelTemp to set
     */
    public void setjLabelTemp(javax.swing.JLabel jLabelTemp) {
        this.jLabelTemp = jLabelTemp;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    /**
     * @return the jPanel5
     */
    public javax.swing.JPanel getjPanel5() {
        return jPanel5;
    }

    /**
     * @param jPanel5 the jPanel5 to set
     */
    public void setjPanel5(javax.swing.JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    /**
     * @return the jLabelEthylen
     */
    public javax.swing.JLabel getjLabelEthylen() {
        return jLabelEthylen;
    }

    /**
     * @param jLabelEthylen the jLabelEthylen to set
     */
    public void setjLabelEthylen(javax.swing.JLabel jLabelEthylen) {
        this.jLabelEthylen = jLabelEthylen;
    }


}
